# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  timeout: 10m


# # all available settings of specific linters
linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  misspell:
    ignore-words:
      - newrelic
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 350 # setting high as tests have long payloads currently
  wsl:
    allow-cuddle-declarations: true
    allow-assign-and-anything: true
  funlen:
    lines: 100
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/newrelic/infrastructure-agent) # Custom section: groups all imports with the specified Prefix.
#      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
  wrapcheck:
    ignoreSigs:
      - multierr.Append
      - errors.Join



linters:
  enable-all: true
  disable:
    # deprecated
    - scopelint
    - interfacer
    - maligned
    - golint
    - deadcode
    - ifshort
    - varcheck
    - structcheck
    - nosnakecase
    # intentionally disabled
    - exhaustivestruct
    - testpackage
    - gci
    - tagliatelle
    - depguard #disabled until configure properly

issues:
  new-from-rev: "HEAD~"
  max-issues-per-linter: 0
  max-same-issues: 0

