name: ~ Windows | Run unit tests

on:
  workflow_call:

env:
  GO_VERSION: '1.18'

jobs:
  test:
    name: Windows unit tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Download deps
        run: go mod vendor

      - name: Running unit tests
        run: build\windows\test.ps1