// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
/*
 * Identity API specifications
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identity
// ConnectResponse struct for ConnectResponse
type ConnectResponse struct {
	Identity Identity `json:"identity"`
	Warnings []string `json:"warnings,omitempty"`
}
