// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
/*
 * Identity API specifications
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identity
// Fingerprint struct for Fingerprint
type Fingerprint struct {
	FullHostname string `json:"fullHostname,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	CloudProviderId string `json:"cloudProviderId,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	BootId string `json:"bootId,omitempty"`
	IpAddresses map[string][]string `json:"ipAddresses,omitempty"`
	MacAddresses map[string][]string `json:"macAddresses,omitempty"`
	Type string `json:"type,omitempty"`
}
