// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
/*
 * Identity API specifications
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identity
// ReRegisterRequest struct for ReRegisterRequest
type ReRegisterRequest struct {
	EntityId int64 `json:"entityId"`
	EntityName string `json:"entityName,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	EntityType string `json:"entityType,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	Source string `json:"source,omitempty"`
}
