name: 'External Runner'
description: 'External Runner'
inputs:
  aws_region:
    description: AWS region.
    required: true
  aws_secret_access_key:
    description: AWS secret access key
    required: true
  aws_access_key_id:
    description: AWS access key id
    required: true
  ecs_cluster_name:
    description: ECS cluster name.
    required: true
  task_definition_name:
    description: Task Definition.
    required: true
  cloud_watch_logs_group_name:
    description: Task Definition.
    required: true
  cloud_watch_logs_stream_name:
    description: Task Definition.
    required: true
  aws_vpc_subnet:
    description: Task Definition.
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v3
      with:
        go-version: '^1.18.3'

    - name: Run external Job
      run: |
        cd ${{ github.action_path }} &&\ 
        go build . &&\
        go run ./external_runner
      shell: bash

      env:
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_REGION: ${{ inputs.aws_region }}
        ECS_CLUSTER_NAME: ${{ inputs.ecs_cluster_name }}
        TASK_DEFINITION_NAME: ${{ inputs.task_definition_name }}
        CLOUD_WATCH_LOGS_GROUP_NAME: ${{ inputs.cloud_watch_logs_group_name }}
        CLOUD_WATCH_LOGS_STREAM_NAME: ${{ inputs.cloud_watch_logs_stream_name }}
        AWS_VPC_SUBNET: ${{ inputs.aws_vpc_subnet }}
