name: 'External Runner'
description: 'External Runner'
inputs:
  aws_region:
    description: AWS region.
    required: true
  ecs_cluster_name:
    description: ECS cluster name.
    required: true
  task_definition_name:
    description: Task Definition.
    required: true
  container_make_target:
    description: Container make target.
    required: true
  cloud_watch_logs_group_name:
    description: Task Definition.
    required: true
  cloud_watch_logs_stream_name:
    description: Task Definition.
    required: true
  aws_vpc_subnet:
    description: Task Definition.
    required: true
  log_filters:
    description: Regexp filters that will be applied to CloudWatch output. To show the full logs add the following filter ".*". By default, it filters Ansible role execution logs.
    default: |
      TASK\s\[.*\]\s
      PLAY\s\[.*\]\s
      PLAY\sRECAP\s
      ok=\d+\s+changed=\d+\s+unreachable=\d+\s+failed=\d+\s+skipped=\d+\s+rescued=\d+\s+ignored=\d+
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.3'

    - name: Run external Job
      run: |
        cd ${{ github.action_path }} && go build . && ./main
      shell: bash

      env:
        AWS_REGION: ${{ inputs.aws_region }}
        ECS_CLUSTER_NAME: ${{ inputs.ecs_cluster_name }}
        TASK_DEFINITION_NAME: ${{ inputs.task_definition_name }}
        CONTAINER_MAKE_TARGET: ${{ inputs.container_make_target }}
        CLOUD_WATCH_LOGS_GROUP_NAME: ${{ inputs.cloud_watch_logs_group_name }}
        CLOUD_WATCH_LOGS_STREAM_NAME: ${{ inputs.cloud_watch_logs_stream_name }}
        AWS_VPC_SUBNET: ${{ inputs.aws_vpc_subnet }}
        LOG_FILTERS: ${{ inputs.log_filters }}
