name: 'External Runner'
description: 'External Runner'
inputs:
  aws_region:
    description: AWS region.
    required: true
  ecs_cluster_name:
    description: ECS cluster name.
    required: true
  task_definition_name:
    description: Task Definition.
    required: true
  cloud_watch_logs_group_name:
    description: Task Definition.
    required: true
  cloud_watch_logs_stream_name:
    description: Task Definition.
    required: true
  aws_vpc_subnet:
    description: Task Definition.
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.3'

    - name: Run external Job
      run: |
        aws ecs run-task --cluster caos_prerelease --task-definition test-prerelease-td --network-configuration “awsvpcConfiguration={subnets=[subnet-09b64de757828cdd4],securityGroups=[sg-096c8a027c6f5904f]}” --launch-type FARGATE
      shell: bash

      env:
        AWS_REGION: ${{ inputs.aws_region }}
        ECS_CLUSTER_NAME: ${{ inputs.ecs_cluster_name }}
        TASK_DEFINITION_NAME: ${{ inputs.task_definition_name }}
        CLOUD_WATCH_LOGS_GROUP_NAME: ${{ inputs.cloud_watch_logs_group_name }}
        CLOUD_WATCH_LOGS_STREAM_NAME: ${{ inputs.cloud_watch_logs_stream_name }}
        AWS_VPC_SUBNET: ${{ inputs.aws_vpc_subnet }}
