name: . 💥🐤 Canaries Prune

on:
  workflow_dispatch:
    inputs:
      platform:
        description: '🐧🪟Limit to platform?'
        type: choice
        default: ''
        options:
          - 'all'
          - 'linux'
          - 'windows'
        required: false
      tag:
        description: 'Tag to prune'
        type: string
        required: true
      A2Q:
          description: 'Should we prune A2Q canaries?'
          type: boolean
          default: false
          required: false

permissions:
  id-token: write

jobs:

  prune-previous-canaries:
    uses: ./.github/workflows/component_canaries_prune.yml
    with:
      PLATFORM: ${{ github.event.inputs.platform }}
      TAG: ${{ github.event.inputs.tag }}
      A2Q: ${{ github.event.inputs.A2Q }}
    secrets:
      AWS_VPC_SUBNET: ${{secrets.AWS_VPC_SUBNET}}
