name: . 🚀 🧹 Clear cache (cloudfare + fastly)

on:
  workflow_dispatch:

jobs:
  purge-cdn:
    name: Purge CDN
    uses: ./.github/workflows/component_purge_cdn.yml
    secrets:
      FASTLY_KEY: ${{secrets.FASTLY_KEY }}
      CLOUDFARE_KEY: ${{secrets.CLOUDFARE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.OHAI_AWS_ACCESS_KEY_ID_PRODUCTION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OHAI_AWS_SECRET_ACCESS_KEY_PRODUCTION }}
      AWS_ROLE_ARN: ${{ secrets.OHAI_AWS_ROLE_ARN_PRODUCTION }}
      AWS_ROLE_SESSION_NAME: ${{ secrets.OHAI_AWS_ROLE_SESSION_NAME_PRODUCTION }}
