name: 🚧 Canary alerts | Prune

on:
  workflow_call:
    secrets:
      AWS_VPC_SUBNET:
        required: true

env:
  AWS_ASSUME_ROLE: 'arn:aws:iam::018789649883:role/caos-pipeline-oidc'
  ANSIBLE_FORKS: 20

permissions:
  id-token: write

jobs:
  provision:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          aws-region: us-east-2

      - name: Removing alerts for canaries
        uses: ./.github/actions/external_runner
        with:
          aws_region: us-east-2
          container_make_target: "provision-alerts-delete/pre-release"
          ecs_cluster_name: caos_prerelease
          task_definition_name: test-prerelease-td
          cloud_watch_logs_group_name: /ecs/test-prerelease
          cloud_watch_logs_stream_name: ecs/test-prerelease
          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
          log_filters: |
            deleting\salerts\sfor