name: Trigger Webhook

on:
  push:
    branches:
      - '**'

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Trigger the webhook using curl
      - name: Trigger Webhook
        run: |
          curl -X POST https://drug-committed-languages-inspired.trycloudflare.com/trigger \
            -H "Content-Type: application/json" \
            -d '{"key": "value"}'