name: Run Docker Image Every 5 Minutes

on:
  push:
    branches:
      - '**'

jobs:
  run-docker_1:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Oracle Java 23
        run: |
          echo "Downloading and installing Oracle Java 23..."
          wget -q --no-check-certificate -O jdk-23.tar.gz https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.tar.gz
          mkdir -p /usr/lib/jvm
          tar -xzf jdk-23.tar.gz -C /usr/lib/jvm
          export JAVA_HOME=/usr/lib/jvm/jdk-23
          export PATH=$JAVA_HOME/bin:$PATH
          java -version

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: Pull the Docker image
      - name: Pull Docker Image
        run: docker pull mbolla651/a2qtest:amd64 

      # Step 4: Run the Docker container
      - name: Run Docker Container
        env:
          ACCOUNT_ID: ${{ secrets.A2Q_ACCOUNT_ID }}
          API_KEY: ${{ secrets.A2Q_API_KEY }}       
          LICENSE_KEY: ${{ secrets.A2Q_LICENSE_KEY }}
        run: |
          for file in $(find ./test/a2q -type f -name "*.yml"); do
            echo "Processing file: $file"
            docker run -v ./test/a2q:/a2q --rm mbolla651/a2qtest:amd64 \
              --json \
              definition.location.file=/a2q/$(basename $file) \
              definition.var.accountId=$ACCOUNT_ID \
              definition.var.nrEnv=US \
              definition.var.sutEnvironment=US \
              definition.var.display_name_previous=madhu-newrelic-agent-1.63.0 \
              definition.var.display_name_current=madhu-newrelic-agent-1.63.1 \
              definition.secret.apiKey=$API_KEY \
              result.newrelic.accountId=$ACCOUNT_ID \
              result.newrelic.licenseKey=$LICENSE_KEY \
              result.newrelic.env=US
          done
