name: .. 🚧 macOS | Run harvest tests

on:
  workflow_call:

jobs:
  harvest-test-macos:
    name: MacOS harvest tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11, macos-12 ]
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Running Harvest tests
        run: |
          # FIXIT: This hack is done because the installed go version is not modified on the env vars
          cp -f `which go` /usr/bin/go 
          sudo -E make linux/harvest-tests
