name: Run Docker Image Every 5 Minutes

on:
  push:
    branches:
      - '**'

jobs:
  run-docker_1:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Environment Variables
        env:
          API_KEY: ${{ secrets.A2Q_API_KEY }}
          ACCOUNT_ID: ${{ secrets.A2Q_ACCOUNT_ID }}
          LICENSE_KEY: ${{ secrets.A2Q_LICENSE_KEY }}
        run: |
          echo "ACCOUNT_ID: ${ACCOUNT_ID:0:5}******" # Mask the account ID for security
          echo "API_KEY: ${API_KEY:0:10}******" # Mask the API key for security
          echo "LICENSE_KEY: ${LICENSE_KEY:0:10}******" # Mask the license key for security


      # Step 3: Test Connectivity to Metric Endpoint
      - name: Test Connectivity to Metric Endpoint
        run: |
          echo "Testing connectivity to https://otlp.nr-data.net:4317/metric/v1..."
          curl -v https://otlp.nr-data.net:4317/metric/v1 || echo "Failed to connect to Metric endpoint"

      # Step 4: Test Connectivity to Events Endpoint
      - name: Test Connectivity to Events Endpoint
        run: |
          echo "Testing connectivity to https://otlp.nr-data.net:4317/v1/accounts/events..."
          curl -v https://otlp.nr-data.net:4317/v1/accounts/events || echo "Failed to connect to Events endpoint"

      - name: Test NRQL Query
        env:
          API_KEY: ${{ secrets.A2Q_API_KEY }} # New Relic API Key stored in GitHub Secrets
          ACCOUNT_ID: ${{ secrets.A2Q_ACCOUNT_ID }} # New Relic Account ID stored in GitHub Secrets
        run: |
          echo "Testing NRQL query to New Relic..."
          curl -X POST "https://insights-api.newrelic.com/v1/accounts/$ACCOUNT_ID/query" \
            -H "X-Query-Key: $API_KEY" \
            -H "Content-Type: application/json" \
            --data '{"nrql": "SELECT count(*) FROM Transaction SINCE 1 minute ago"}'

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: Pull the Docker image
      - name: Pull Docker Image
        run: docker pull mbolla651/a2qtest:amd64

      # Step 4: Run the Docker container
      - name: Run Docker Container
        timeout-minutes: 15
        env:
          ACCOUNT_ID: ${{ secrets.A2Q_ACCOUNT_ID }}
          API_KEY: ${{ secrets.A2Q_API_KEY }}
          LICENSE_KEY: ${{ secrets.A2Q_LICENSE_KEY }}
        run: |
          for file in $(find ./test/a2q -type f -name "*.yml"); do
            echo "Processing file: $file"
            docker run --name a2qtest-container -v ./test/a2q:/a2q --rm mbolla651/a2qtest:amd64 \
              --json \
              definition.location.file=/a2q/$(basename $file) \
              definition.var.accountId=$ACCOUNT_ID \
              definition.var.nrEnv=US \
              definition.var.sutEnvironment=US \
              definition.var.display_name_previous=madhu-newrelic-agent-1.63.0 \
              definition.var.display_name_current=madhu-newrelic-agent-1.63.1 \
              definition.secret.apiKey=$API_KEY \
              result.newrelic.accountId=$ACCOUNT_ID \
              result.newrelic.licenseKey=$LICENSE_KEY \
              result.newrelic.env=US || docker logs a2qtest-container
          done
