name: .. 🚧 Linux | Compile binaries

on:
  workflow_call:
    secrets:
      DOCKER_HUB_ID:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
    inputs:
      TAG:
        required: true
        type: string

env:
  TAG: ${{ inputs.TAG }}

jobs:
  test-build:
    name: Test binary compilation for all (linux) platforms:arch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build all platforms:arch
        run: make ci/build
      - name: Test FIPS binaries for fips compliance
        uses: newrelic/coreint-automation/test-fips-action@v3
        with:
          binaries_path: "./dist"
