name: Run Binary from Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  run-binary:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up the environment
      - name: Set up Environment Variables
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        run: |
          echo "Environment variables set."

      # Step 2: Run NRQL Query
      - name: Run NRQL Query
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        run: |
          echo "Running NRQL query in New Relic..."
          curl -X POST https://api.newrelic.com/graphql \
            -H "Content-Type: application/json" \
            -H "API-Key: $NEW_RELIC_API_KEY" \
            --data '{
              "query": "{
                actor {
                  account(id: '$ACCOUNT_ID') {
                    nrql(query: \"SELECT count(*) FROM Transaction SINCE 30 minutes ago\") {
                      results
                    }
                  }
                }
              }"
            }' > nrql_response.json

          echo "NRQL Query Response:"
          cat nrql_response.json