name: . 🚀 🍏 Prerelease Macos

on:
  release:
    types:
      - prereleased
    tags:
      - '*'


permissions:
  contents: read

jobs:
  unit-test:
    uses: ./.github/workflows/component_macos_unit_test.yml

  canaries-macos:
    permissions:
      contents: read
      id-token: write # calls component_canaries.yml which needs AWS OIDC auth
    uses: ./.github/workflows/component_canaries.yml
    with:
      PLATFORM: "macos"
      TAG: ${{ github.event.release.tag_name }}
    secrets:
      AWS_VPC_SUBNET: ${{secrets.AWS_VPC_SUBNET}}
