name: External task POC

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run-external_job:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Upload checksums file
        uses: ./.github/actions/external_runner
        with:
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_region: us-east-2
          ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
          task_definition_name: ${{ secrets.TASK_DEFINITION_NAME }}
          cloud_watch_logs_group_name: ${{ secrets.CLOUD_WATCH_LOGS_GROUP_NAME }}
          cloud_watch_logs_stream_name: ${{ secrets.CLOUD_WATCH_LOGS_STREAM_NAME }}
          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
