on:
  push:

jobs:
  molecule-test-packages:
    name: Test package installation
    runs-on: ubuntu-latest
    steps:
      - uses: newrelic/pkg-installation-testing-action@v1
        with:
          gpg_key: 'https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg'
          repo_base_url: 'http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/dadams_fips_current'
          package_name: 'newrelic-infra'
          package_version: '0.1.0'
          platforms: "al2,al2023,debian-bullseye,debian-bookworm,redhat8,redhat9,suse15.3,suse15.4,ubuntu1604,ubuntu1804,ubuntu2004,ubuntu2204,ubuntu2404"
