name: Test Windows Container Build

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Version tag for the build (e.g., 1.0.0)'
        required: true
        default: '0.0.0'
      PUBLISH:
        description: 'Publish to Docker Hub'
        required: false
        type: boolean
        default: false

jobs:
  build-windows-container:
    name: Build and test Windows container
    uses: ./.github/workflows/component_docker_build_windows.yml
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      PFX_CERTIFICATE_BASE64: ${{ secrets.OHAI_PFX_CERTIFICATE_BASE64 }}
      PFX_PASSPHRASE: ${{ secrets.OHAI_PFX_PASSPHRASE }}
    with:
      TAG: ${{ inputs.TAG }}
      PUBLISH: ${{ inputs.PUBLISH }}
